### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by Listlessness** [theneuetimes/fuseball#16]
When I run it I get a 502 Error

**Comment by Listlessness** [comment]
Failed to load resource: the server responded with a status of 502 ()

**Comment by theneuetimes** [comment]
Are you using the "npm start" command to run it?

**Comment by Listlessness** [comment]
Yes

**Comment by theneuetimes** [comment]
This seems to be an issue specific to your machine. Can you screenshot exactly what you see in the browser console?
